name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cat .env >> $GITHUB_ENV

      - name: Use the value
        run: echo $FOO
